spring:
  application:
    name: user-api
  datasource:
    url: jdbc:mysql://rm-2zee878d65v2tw3idao.mysql.rds.aliyuncs.com/micro_service_in_action?characterEncoding=utf8
    username: root
    password: 19881122yl^
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
server:
  ssl:
    ## 生成证书的命令：keytool -genkeypair -alias jerry -keyalg RSA -keystore .\jerry.key
    key-store: classpath:jerry.key
    key-store-password: 123456
    key-password: 123456